# Generated by Django 4.1.6 on 2023-02-12 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('length', models.CharField(max_length=120)),
                ('year', models.DateField(auto_now_add=True)),
                ('genre', models.TextField()),
            ],
        ),
    ]
